version: '3.8'

services:
    db:
        container_name: postgres
        image: postgres:9.6
        ports:
          - ${host_connect}:5432
        environment:
            - POSTGRES_USER: ${DB_USER}
            - POSTGRES_PASSWORD: ${DB_PASSWORD}
            - POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - ./pgdata:/var/lib/postgresql/data
    dev:
        container_name: managerbran/vartisan-dev
        image: nestjs-vartisan-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: managerbran/vartisan-prod
        image:  nestjs-vartisan-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    nesjs-network: